import { ArrowRight, ArrowUpRight, Briefcase, Code2, Download, Github, GraduationCap, Linkedin, Mail, MapPin, Menu, MessageCircle, Server, X } from 'lucide-react';
import { useState } from 'react';
import PrivacyPolicy from './components/PrivacyPolicy';
const projects=[
{name:'DK Garage',type:'Automotive Marketplace',image:'/dkv.jpg',url:'https://dk-vroom-ten.vercel.app/',desc:'A premium automotive marketplace designed for the Malaysian vehicle market. The platform brings car rental, purchasing, repairs, insurance, auctions, and financing into one experience. Users can explore services and vehicles from verified dealers through a modern interface. The product is structured as an automotive super app that works smoothly across devices.',stack:['Marketplace','Automotive']},
{name:'View Before You Move',type:'VR Property Portal',image:'/viewbefore.jpg',url:'https://viewbeforeyoumove.com/',desc:'An immersive VR-first property portal designed to support confident real-estate decisions. Visitors can explore VR-enabled properties before arranging an in-person move or viewing. The calm visual presentation keeps listings clear, trustworthy, and easy to compare. The experience combines property discovery with modern interactive technology across devices.',stack:['Property Tech','VR Experience']},
{name:'GoBeagleGo',type:'Digital Platform',image:'/gobeaglego.jpg',url:'https://gobeaglego.com/',desc:'A distinctive digital platform built around the GoBeagleGo brand and its online services. The website uses a focused interface to introduce the offering and guide users through its core experience. Responsive components keep content accessible across desktop and mobile screens. Clear interaction patterns help visitors move naturally from discovery to action.',stack:['Web Platform','Responsive']},
{name:'Digital Universe',type:'Digital Agency',image:'/digitals.jpg',url:'https://www.digitaluniverse.agency/',desc:'A conversion-focused agency website for businesses in Dubai and across the UAE. It presents web design, SEO, social media, branding, and e-commerce services in a unified experience. Portfolio content and strong calls to action establish expertise and encourage consultation requests. The responsive presentation supports both local search visibility and premium brand positioning.',stack:['Agency Website','Dubai UAE']},
{name:'CHEMfix',type:'Construction Chemicals',image:'/chemfix.jpg',url:'https://chemfix.org/',desc:'A comprehensive corporate platform for a specialist construction-chemicals supplier. It presents waterproofing, concrete repair, flooring, grouts, sealants, coatings, and road-safety systems. Product categories are structured to help contractors and industry clients find relevant solutions quickly. The professional responsive design reinforces technical credibility and supports enquiries.',stack:['Corporate Site','Product Catalog']},
{name:'C2M Imports',type:'Home Finishing',image:'/c2m.jpg',url:'https://c2mimports.com/',desc:'A turnkey home-completion website for an importation and installation company in Mauritius. It showcases electrical, plumbing, kitchen, bathroom, appliance, and final-setup solutions. The site turns a broad service offering into a clear journey for homeowners and property clients. Visual service sections and direct enquiry paths make planning a finished home easier.',stack:['Service Platform','Mauritius']},
{name:'ABSMD',type:'Healthcare Platform',image:'/absmd.png',url:'https://absmd.us/',desc:'A professional medical billing platform designed for healthcare providers in Georgia. It presents billing, coding, credentialing, and support services with a clear information structure. Trust signals and focused calls to action help visitors understand the company quickly. The responsive interface keeps complex healthcare content accessible across every device.',stack:['React','Responsive UI']},
{name:'BIM Africa',type:'Digital Agency',image:'/bim.png',url:'https://www.bim.africa/',desc:'A modern digital agency platform created for an international African market. The website brings web development, SEO, social media, and 3D services into one cohesive experience. Strong visual sections make the agency’s capabilities and portfolio easy to explore. Its responsive structure supports both lead generation and brand credibility.',stack:['Next.js','Full Stack']},
{name:'Mauritius Travel Tour',type:'Travel & Booking',image:'/travel.png',url:'https://maurituistraveltour.com/',desc:'A destination-focused travel website for discovering tours and experiences across Mauritius. Visitors can explore activities, understand itineraries, and move naturally toward making a reservation. Rich imagery gives each destination a strong sense of place. The mobile-first layout makes trip planning simple while travelling.',stack:['Booking','REST API']},
{name:'Hawar Homes',type:'Real Estate',image:'/hawar.png',url:'https://hawarhomes.com/',desc:'A premium real-estate experience for luxury vacation rentals in Dubai. The platform presents high-quality properties with clear details, strong imagery, and direct enquiry paths. Its design reflects the expectations of international guests and property owners. Responsive navigation keeps property discovery smooth on mobile and desktop.',stack:['React','Lead Generation']},
{name:'Flash Wash',type:'Automotive Services',image:'/flash.png',url:'https://flashwash.mu/',desc:'A fast and friendly service website for an automatic car wash in Mauritius. Customers can compare wash packages, understand the benefits, and find essential business information quickly. The interface uses clear pricing and conversion-focused calls to action. A responsive layout ensures the experience works especially well for mobile visitors.',stack:['Service Website','Mobile First']},
{name:'Hoda Shine',type:'Home Services',image:'/hoda.png',url:'https://hodashineservices.com/',desc:'A lead-generation website for professional cleaning services across Ajman, Dubai, and Sharjah. The experience explains available services, coverage areas, and eco-friendly cleaning options. Direct contact paths help customers request assistance without unnecessary steps. Its approachable design builds trust while keeping the content easy to scan.',stack:['Business Website','UAE']},
{name:'Al Karak',type:'Business Website',image:'/alkaram.jpg',url:'https://alkarak-tau.vercel.app/',desc:'A polished business website created to present the Al Karak brand and its services online. The layout organizes company information into clear, accessible sections for prospective customers. Strong visual hierarchy makes important offerings and contact actions easy to identify. The responsive build provides a consistent experience across screen sizes.',stack:['React','Vercel']}
];
const experience=[
['Apr – May 2026','90 Solutions','MERN & Zoho CRM Developer','Customized Zoho CRM using workflows, blueprints, automations, and Deluge scripting. Built structured lead-management processes that reduced repetitive manual work and supported smoother client operations. Integrated third-party APIs and connected MERN-based functionality with CRM workflows. Worked remotely on planning, implementation, testing, and delivery.'],
['Aug 2025 – Apr 2026','BIM Africa','MERN Stack Developer','Built and maintained full-stack applications for international business clients using React, Next.js, Node.js, Express, and MongoDB. Created responsive interfaces, secure REST APIs, JWT authentication, and structured database schemas. Owned features from early planning through production deployment. Improved usability, performance, and the overall customer experience across multiple client products.'],
['Sep 2025 – Mar 2026','Cyber Nexus','MERN Stack Developer','Developed modular web applications with reusable React components and scalable Express and MongoDB backends. Collaborated with the development team through Git-based workflows and code review. Handled API integration, debugging, testing, and performance improvements. Contributed maintainable code while working across both frontend and backend features.'],
['Aug 2025 – Jan 2026','Freelance · UAE Clients','Full Stack Developer','Delivered responsive business and service websites for UAE-based clients from design handoff to production. Converted UI and UX concepts into maintainable React applications and integrated APIs and authentication where required. Managed Vercel deployment, custom domains, DNS configuration, and SSL setup. Communicated directly with clients and delivered complete solutions around their business requirements.'],
['Feb – May 2025','Digital Brains','Web Developer Intern','Built reusable React and Tailwind CSS interface components for MERN applications. Supported feature development, debugging, browser testing, and responsive design improvements. Used Git and version control while collaborating with the wider development team. Strengthened practical understanding of component architecture and production development workflows.']
];
const skills: [string, string[]][] =[['Frontend',['React.js','Next.js','JavaScript ES6+','Tailwind CSS','Responsive Design','Cross-Browser UI']],['Backend & Architecture',['Node.js','Express.js','MongoDB','Mongoose','REST APIs','JWT Authentication','MVC Structure','Schema Design']],['Deployment & Tools',['Vercel Deployment','Domain Configuration','DNS Management','SSL Setup','Git & GitHub','Postman','npm & Vite','Production Builds']],['AI & Automation',['AI-Assisted Development','Code Generation Workflows','AI Debugging Support','Prompt-Based Prototyping','Zoho CRM Automation','Deluge Scripting','Workflow Automation','API Integration']]];
export default function App(){const[open,setOpen]=useState(false);if(location.pathname==='/privacy-policy')return <PrivacyPolicy/>;return <main><nav><a className="logo" href="#home"><Code2/> Hassan<span>.</span></a><div className={open?'open':''}>{['Home','About','Skills','Projects','Experience','Contact'].map(x=><a href={`#${x.toLowerCase()}`} onClick={()=>setOpen(false)}>{x}</a>)}</div><a className="cv" href="/Muhammad_Hassan_Resume.docx" download><Download/> Download CV</a><button className="menu" type="button" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?<X/>:<Menu/>}</button></nav>
<section className="hero" id="home"><div className="hero-copy"><div className="available"><i/> Available for freelance & remote roles</div><p className="hello">HELLO, I’M</p><h1>Muhammad<br/><span>Hassan.</span></h1><h2>Full Stack MERN Developer</h2><p className="summary">I build responsive, scalable web applications with thoughtful interfaces and reliable backends—from planning and development to deployment.</p><div className="actions"><a className="primary" href="#projects">View my work <ArrowRight/></a><a className="secondary" href="mailto:info@hassanomar.site"><Mail/> Contact me</a></div><div className="social"><a href="https://github.com/Hassan-Omar03"><Github/> GitHub</a><a href="https://www.linkedin.com/in/mohammad-hassan-6919aa111/"><Linkedin/> LinkedIn</a><span><MapPin/> Punjab, Pakistan</span></div><div className="hero-stats"><div><b>10+</b><span>Production projects</span></div><div><b>5</b><span>Professional roles</span></div><div><b>100%</b><span>Remote ready</span></div></div></div><div className="hero-visual"><div className="photo-frame"><img src="/me.jpeg" alt="Muhammad Hassan, Full Stack MERN Developer in Pakistan" width="342" height="417"/></div></div></section>
<section className="about section" id="about"><div className="heading"><span>ABOUT ME</span><h2>A developer focused on<br/>real business results.</h2><p>I turn requirements and designs into fast, secure, production-ready applications.</p></div><div className="about-grid"><div className="about-copy"><p>I specialize in the MERN stack, combining polished React and Next.js interfaces with secure Node.js, Express, and MongoDB backends.</p><p>I’m comfortable owning the complete project lifecycle—including architecture, API integration, authentication, deployment, domain configuration, and SSL setup.</p><a href="/Muhammad_Hassan_Resume.docx" download>Read my résumé <ArrowUpRight/></a></div><div className="about-cards"><div><Briefcase/><b>Professional Experience</b><p>Agency, contract, internship, and international freelance work.</p></div><div><GraduationCap/><b>Computer Science</b><p>GCU Faisalabad graduate with one-year MERN training.</p></div></div></div></section>
<section className="skills section" id="skills"><div className="heading"><span>MY SKILLS</span><h2>Technologies I work with</h2><p>A practical toolkit for building and shipping complete web products.</p></div><div className="skill-grid">{skills.map((s,i)=><div className="skill-card"><div className="skill-title">{i===0?<Code2/>:<Server/>}<h3>{s[0]}</h3></div>{s[1].map(x=><span>{x}</span>)}</div>)}</div></section>
<section className="projects section" id="projects"><div className="heading row"><div><span>SELECTED PROJECTS</span><h2>Some of my recent work</h2></div><a href="https://github.com/Hassan-Omar03">View GitHub <ArrowUpRight/></a></div><div className="projects-grid">{projects.map(p=><a className="project" href={p.url} target="_blank" rel="noreferrer"><div className="project-img"><img src={p.image} alt={`${p.name} web development project by Muhammad Hassan`} loading="lazy"/><span>Live site <ArrowUpRight/></span></div><div className="project-info"><small>{p.type}</small><h3>{p.name}</h3><p>{p.desc}</p><div>{p.stack.map(x=><b>{x}</b>)}</div></div></a>)}</div></section>
<section className="experience section" id="experience"><div className="heading"><span>EXPERIENCE</span><h2>My professional journey</h2></div><div className="timeline">{experience.map((e,i)=><article><div className="dot">{i+1}</div><time>{e[0]}</time><div><h3>{e[2]}</h3><b>{e[1]}</b><p>{e[3]}</p></div></article>)}</div></section>
<section className="contact section" id="contact"><div><span>LET’S WORK TOGETHER</span><h2>Have a project in mind?</h2><p>I’m available for freelance projects, remote roles, and collaborations. Let’s discuss how I can help.</p><a className="primary" href="mailto:info@hassanomar.site"><Mail/> Send me an email</a></div><aside><a href="mailto:info@hassanomar.site"><Mail/><span>Email<b>info@hassanomar.site</b></span></a><a href="https://wa.me/923247305909"><MessageCircle/><span>WhatsApp<b>+92 324 7305909</b></span></a><a href="https://github.com/Hassan-Omar03"><Github/><span>GitHub<b>Hassan-Omar03</b></span></a></aside></section><footer>© {new Date().getFullYear()} Muhammad Hassan <a href="/privacy-policy">Privacy Policy</a></footer></main>}








