import { ArrowRight, ArrowUpRight, Briefcase, Code2, Download, Github, GraduationCap, Linkedin, Mail, MapPin, Menu, MessageCircle, Phone, Clock, Send, Server, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import PrivacyPolicy from './components/PrivacyPolicy';
const projects=[
{name:'DK Garage',type:'Automotive Marketplace',image:'/dkv.jpg',url:'https://dk-vroom-ten.vercel.app/',desc:'A premium automotive marketplace designed for the Malaysian vehicle market. The platform brings car rental, purchasing, repairs, insurance, auctions, and financing into one experience. Users can explore services and vehicles from verified dealers through a modern interface. The product is structured as an automotive super app that works smoothly across devices.',stack:['Marketplace','Automotive']},
{name:'View Before You Move',type:'VR Property Portal',image:'/viewbefore.jpg',url:'https://viewbeforeyoumove.com/',desc:'An immersive VR-first property portal designed to support confident real-estate decisions. Visitors can explore VR-enabled properties before arranging an in-person move or viewing. The calm visual presentation keeps listings clear, trustworthy, and easy to compare. The experience combines property discovery with modern interactive technology across devices.',stack:['Property Tech','VR Experience']},
{name:'GoBeagleGo',type:'Digital Platform',image:'/gobeaglego.jpg',url:'https://gobeaglego.com/',desc:'A distinctive digital platform built around the GoBeagleGo brand and its online services. The website uses a focused interface to introduce the offering and guide users through its core experience. Responsive components keep content accessible across desktop and mobile screens. Clear interaction patterns help visitors move naturally from discovery to action.',stack:['Web Platform','Responsive']},
{name:'Digital Universe',type:'Digital Agency',image:'/digitals.jpg',url:'https://www.digitaluniverse.agency/',desc:'A conversion-focused agency website for businesses in Dubai and across the UAE. It presents web design, SEO, social media, branding, and e-commerce services in a unified experience. Portfolio content and strong calls to action establish expertise and encourage consultation requests. The responsive presentation supports both local search visibility and premium brand positioning.',stack:['Agency Website','Dubai UAE']},
{name:'CHEMfix',type:'Construction Chemicals',image:'/chemfix.jpg',url:'https://chemfix.org/',desc:'A comprehensive corporate platform for a specialist construction-chemicals supplier. It presents waterproofing, concrete repair, flooring, grouts, sealants, coatings, and road-safety systems. Product categories are structured to help contractors and industry clients find relevant solutions quickly. The professional responsive design reinforces technical credibility and supports enquiries.',stack:['Corporate Site','Product Catalog']},
{name:'C2M Imports',type:'Home Finishing',image:'/c2m.jpg',url:'https://c2mimports.com/',desc:'A turnkey home-completion website for an importation and installation company in Mauritius. It showcases electrical, plumbing, kitchen, bathroom, appliance, and final-setup solutions. The site turns a broad service offering into a clear journey for homeowners and property clients. Visual service sections and direct enquiry paths make planning a finished home easier.',stack:['Service Platform','Mauritius']},
{name:'AbsMD LLC',type:'Medical Billing',image:'/absmd.png',url:'https://absmd.us/',desc:'A professional website for an affordable medical billing company serving healthcare practices in Georgia. It explains billing, practice-management, coding, credentialing, and reimbursement support. The content helps providers understand how AbsMD can streamline administrative operations. Clear service information and enquiry paths support trust and client acquisition.',stack:['Healthcare','Business Website']},
{name:'Mauritius Travel & Tour',type:'Travel & Tours',image:'/travel.png',url:'https://mauritiustraveltour.com/',desc:'A Mauritius tour platform helping visitors discover experiences across the north, south, east, and west of the island. It presents guided tours, airport transfers, customized requests, and organizer information. Destination-focused visuals make activities easy to explore. Clear booking and contact paths help travelers plan an experience that matches their interests.',stack:['Tours','Booking']},
{name:'Hawar Vacation Homes',type:'Luxury Rentals',image:'/hawar.png',url:'https://hawarhomes.com/',desc:'A luxury short-term rental website for fully furnished apartments and villas across Dubai. It covers premium locations including Downtown Dubai, Business Bay, Palm Jumeirah, Dubai Hills, and Bluewaters Island. Property-focused presentation supports both discovery and direct enquiries. The brand is presented as a Dubai DET-licensed vacation-home provider.',stack:['Real Estate','Dubai']},
{name:'Flash Wash Mauritius',type:'Automatic Car Wash',image:'/flash.png',url:'https://flashwash.mu/',desc:'A service website for an automatic tunnel car wash in Central Flacq, Mauritius. It presents a fast five-minute exterior and interior wash experience with eco-friendly water recycling. Customers can understand available services and plan their visit easily. The site also highlights the Steam & Bean coffee experience available while customers wait.',stack:['Automotive','Mauritius']},
{name:'Hoda Shine Services',type:'Cleaning Services',image:'/hoda.png',url:'https://hodashineservices.com/',desc:'A professional cleaning-services website covering Ajman, Sharjah, and Dubai. It presents home and office cleaning, deep cleaning, sofa cleaning, carpet cleaning, and hourly maid services. Visitors can quickly understand available options and service areas. Direct enquiry paths help customers connect with the team for trusted UAE cleaning support.',stack:['Cleaning','UAE']},
{name:'Al Karam Real Estate',type:'Real Estate',image:'/alkaram.jpg',url:'https://alkaram-tau.vercel.app/',desc:'A real-estate platform for Al Karam Real Estate, an authorized sub-dealer of Al Jalil Developers in Lahore. The website presents residential opportunities in Al Noor Orchard and Al Jalil Garden. Visitors can explore the agency, understand available developments, and contact the team directly. The experience is designed to build trust and generate qualified property enquiries.',stack:['React','Real Estate']},
];
const experience=[
['Apr – May 2026','90 Solutions','MERN & Zoho CRM Developer','Customized Zoho CRM using workflows, blueprints, automations, and Deluge scripting. Built structured lead-management processes that reduced repetitive manual work and supported smoother client operations. Integrated third-party APIs and connected MERN-based functionality with CRM workflows. Worked remotely on planning, implementation, testing, and delivery.'],
['Aug 2025 – Apr 2026','BIM Africa','MERN Stack Developer','Built and maintained full-stack applications for international business clients using React, Next.js, Node.js, Express, and MongoDB. Created responsive interfaces, secure REST APIs, JWT authentication, and structured database schemas. Owned features from early planning through production deployment. Improved usability, performance, and the overall customer experience across multiple client products.'],
['Sep 2025 – Mar 2026','Cyber Nexus','MERN Stack Developer','Developed modular web applications with reusable React components and scalable Express and MongoDB backends. Collaborated with the development team through Git-based workflows and code review. Handled API integration, debugging, testing, and performance improvements. Contributed maintainable code while working across both frontend and backend features.'],
['Aug 2025 – Jan 2026','Freelance · UAE Clients','Full Stack Developer','Delivered responsive business and service websites for UAE-based clients from design handoff to production. Converted UI and UX concepts into maintainable React applications and integrated APIs and authentication where required. Managed Vercel deployment, custom domains, DNS configuration, and SSL setup. Communicated directly with clients and delivered complete solutions around their business requirements.'],
['Feb – May 2025','Digital Brains','Web Developer Intern','Built reusable React and Tailwind CSS interface components for MERN applications. Supported feature development, debugging, browser testing, and responsive design improvements. Used Git and version control while collaborating with the wider development team. Strengthened practical understanding of component architecture and production development workflows.']
];
const skills: [string, string[]][] =[['Frontend',['React.js','Next.js','JavaScript ES6+','Tailwind CSS','Responsive Design','Cross-Browser UI']],['Backend & Architecture',['Node.js','Express.js','MongoDB','Mongoose','REST APIs','JWT Authentication','MVC Structure','Schema Design']],['Deployment & Tools',['Vercel Deployment','Domain Configuration','DNS Management','SSL Setup','Git & GitHub','Postman','npm & Vite','Production Builds']],['AI & Automation',['AI-Assisted Development','Code Generation Workflows','AI Debugging Support','Prompt-Based Prototyping','Zoho CRM Automation','Deluge Scripting','Workflow Automation','API Integration']]];
const roles=['Backend Engineer','Full-Stack Developer','MERN Stack Developer','API & AI Integration Developer'];
const services=[['MERN Stack','Full-Stack Web Development','Building fast, scalable, and secure web applications using the MERN stack — MongoDB, Express.js, React, and Node.js.'],['OpenAI · TensorFlow','AI Integration','Implementing AI-powered features like chatbots, recommendations, and image recognition via OpenAI APIs or TensorFlow models.'],['All Devices','Responsive UI/UX','Crafting mobile-friendly, cross-device experiences that look great and perform smoothly across all screen sizes.'],['JWT · OAuth · Firebase','Auth & Security','Implementing secure user authentication systems using JWT, OAuth, Firebase Auth, and third-party providers.'],['REST · GraphQL','API Design & Integration','Designing and consuming RESTful APIs, GraphQL endpoints, and third-party services for seamless data flow.'],['Vercel · Netlify · CI/CD','Deployment & DevOps','Deploying and managing full-stack applications on Vercel, Netlify, and Firebase with automated CI/CD pipelines.']];
export default function App(){const[open,setOpen]=useState(false);const[roleIndex,setRoleIndex]=useState(0);const[formStatus,setFormStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle');const handleContact=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setFormStatus('sending');const form=event.currentTarget;const data=new FormData(form);data.append('_subject',String(data.get('subject')||'Portfolio inquiry'));data.append('_template','table');data.append('_captcha','false');try{const response=await fetch('https://formsubmit.co/ajax/info@hassanomar.site',{method:'POST',body:data,headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Submission failed');setFormStatus('sent');form.reset()}catch{setFormStatus('error')}};useEffect(()=>{const timer=window.setInterval(()=>setRoleIndex(current=>(current+1)%roles.length),2400);return()=>window.clearInterval(timer)},[]);if(location.pathname==='/privacy-policy')return <PrivacyPolicy/>;return <main><nav><a className="logo" href="#home" aria-label="Muhammad Hassan home"><span className="mh-mark"><b>M</b><b>H</b></span><strong>Muhammad Hassan</strong></a><div className={open?'open':''}>{['Home','About','Services','Skills','Projects','Experience','Contact'].map(x=><a href={`#${x.toLowerCase()}`} onClick={()=>setOpen(false)}>{x}</a>)}</div><a className="cv" href="/Muhammad_Hassan_Resume.docx" download><Download/> Download CV</a><button className="menu" type="button" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?<X/>:<Menu/>}</button></nav>
<section className="hero" id="home"><div className="hero-copy"><p className="hello">HELLO, I’M</p><h1>Muhammad<br/><span>Hassan.</span></h1><h2 className="role-line"><span key={roleIndex}>{roles[roleIndex]}</span><i/></h2><p className="summary">I build responsive, scalable web applications with thoughtful interfaces and reliable backends—from planning and development to deployment.</p><div className="actions"><a className="primary" href="#projects">View my work <ArrowRight/></a><a className="secondary" href="mailto:info@hassanomar.site"><Mail/> Contact me</a></div></div><div className="hero-visual"><div className="delivery-panel"><header><div><small>HOW I BUILD</small><h3>Product Delivery System</h3></div><span>End-to-end</span></header><div className="delivery-flow"><article><b>01</b><div><h4>Plan</h4><p>Requirements, architecture, and scalable data structure.</p></div></article><article><b>02</b><div><h4>Build</h4><p>Responsive interface, secure APIs, and authentication.</p></div></article><article><b>03</b><div><h4>Ship</h4><p>Testing, performance, deployment, DNS, and SSL.</p></div></article></div><footer><span><i/> Production focused</span><span>React · Node · MongoDB</span></footer></div></div><div className="hero-bottom"><div className="hero-contact"><a href="mailto:info@hassanomar.site"><small>EMAIL</small><b>info@hassanomar.site</b></a><a href="tel:+923247305909"><small>PHONE</small><b>+92 324 7305909</b></a><span><small>LOCATION</small><b>Punjab, Pakistan</b></span></div><div className="hero-stats"><div><b>10+</b><span>Production projects</span></div><div><b>5</b><span>Professional roles</span></div><div><b>Full</b><span>Project delivery</span></div></div></div></section>
<section className="about section" id="about"><div className="heading"><span>ABOUT ME</span><h2>A developer focused on<br/>real business results.</h2><p>I turn requirements and designs into fast, secure, production-ready applications.</p></div><div className="about-grid"><div className="about-intro"><div className="about-photo"><img src="/me.jpeg" alt="Muhammad Hassan"/></div><div className="about-copy"><p>I am a Full Stack Web Developer specializing in the MERN stack, with hands-on experience delivering responsive and scalable applications for clients across real estate, travel, healthcare, construction, automotive, and service industries.</p><p>On the frontend, I build production-ready interfaces with React.js, Next.js, JavaScript, and Tailwind CSS. My focus is responsive behavior, reusable components, cross-browser consistency, and interfaces that support real business goals.</p><p>On the backend, I work with Node.js, Express.js, MongoDB, Mongoose, REST APIs, structured schemas, CRUD operations, and JWT authentication. I plan applications around maintainable architecture and reliable data flow.</p><p>I can own the complete project lifecycle from planning and development to testing, Vercel deployment, custom domains, DNS configuration, and SSL setup. I also work with Zoho CRM, Deluge automation, third-party integrations, and AI-assisted development.</p><a href="/Muhammad_Hassan_Resume.docx" download>Read my résumé <ArrowUpRight/></a></div></div><div className="about-cards"><div><Briefcase/><b>Professional Experience</b><p>Delivered production MERN and CRM solutions with 90 Solutions, BIM Africa, Cyber Nexus, Digital Brains, and international freelance clients.</p></div><div><GraduationCap/><b>Computer Science</b><p>BS Computer Science from GCU Faisalabad, plus a one-year MERN Stack Development program from Saylani Mass IT Program.</p></div></div></div></section>
<section className="services section" id="services"><div className="heading"><span>WHAT I OFFER</span><h2>Services built around your goals</h2><p>Complete development solutions for modern digital products.</p></div><div className="service-grid">{services.map((s,i)=><article key={s[1]}><div className="service-number">0{i+1}</div><small>{s[0]}</small><h3>{s[1]}</h3><p>{s[2]}</p></article>)}</div></section><section className="skills section" id="skills"><div className="heading"><span>MY SKILLS</span><h2>Technologies I work with</h2><p>A practical toolkit for building and shipping complete web products.</p></div><div className="skill-grid">{skills.map((s,i)=><div className="skill-card"><div className="skill-title">{i===0?<Code2/>:<Server/>}<h3>{s[0]}</h3></div>{s[1].map(x=><span>{x}</span>)}</div>)}</div></section>
<section className="projects section" id="projects"><div className="heading row"><div><span>SELECTED PROJECTS</span><h2>Some of my recent work</h2></div><a href="https://github.com/Hassan-Omar03">View GitHub <ArrowUpRight/></a></div><div className="projects-grid">{projects.map(p=><a className="project" href={p.url} target="_blank" rel="noreferrer"><div className="project-img"><img src={p.image} alt={`${p.name} web development project by Muhammad Hassan`} loading="lazy"/><span>Live site <ArrowUpRight/></span></div><div className="project-info"><small>{p.type}</small><h3>{p.name}</h3><p>{p.desc}</p><div>{p.stack.map(x=><b>{x}</b>)}</div></div></a>)}</div></section>
<section className="background-section section" id="experience"><div className="heading"><span>MY BACKGROUND</span><h2>Career &amp; Learning</h2><p>Academic foundations and practical experience that shaped how I build software.</p></div><div className="background-grid"><div className="background-column education-column"><header><small>LEARNING</small><h3>Education</h3></header><div className="background-timeline"><article><time>Graduated</time><div><small>Government College University, Faisalabad</small><h4>Bachelor of Computer Science</h4><p>Completed a Computer Science degree with a strong foundation in software development, programming concepts, databases, and analytical problem solving.</p></div></article><article><time>2023 — 2024</time><div><small>Saylani Mass IT Program</small><h4>MERN Stack Development</h4><p>Completed an intensive one-year program covering authentication, CRUD applications, REST APIs, backend architecture, database design, and production deployment.</p></div></article></div></div><div className="background-column experience-column"><header><small>PRACTICE</small><h3>Experience</h3></header><div className="background-timeline">{experience.map(e=><article key={e[1]}><time>{e[0]}</time><div><small>{e[1]}</small><h4>{e[2]}</h4><p>{e[3]}</p></div></article>)}</div></div></div></section>
<section className="contact-section section" id="contact"><div className="heading"><span>GET IN TOUCH</span><h2>Write Your Message</h2><p>If you have a project or professional inquiry, complete the form and I’ll get back to you as soon as possible.</p></div><div className="contact-layout"><form className="contact-form" onSubmit={handleContact}><div className="form-row"><label><span>Name</span><input name="name" type="text" placeholder="Your name" required/></label><label><span>Email</span><input name="email" type="email" placeholder="you@example.com" required/></label></div><label><span>Subject</span><input name="subject" type="text" placeholder="Project or inquiry subject" required/></label><label><span>Message</span><textarea name="message" rows={7} placeholder="Tell me about your project or inquiry..." required/></label><button type="submit" disabled={formStatus==='sending'}>{formStatus==='sending'?'Sending...':'Submit message'} <Send/></button>{formStatus==='sent'&&<p className="form-success">Message sent successfully. I will respond soon.</p>}{formStatus==='error'&&<p className="form-error">Message could not be sent. Please email info@hassanomar.site directly.</p>}</form><aside className="contact-details"><div><MapPin/><span><small>Address</small><b>Punjab, Pakistan</b></span></div><div><Phone/><span><small>Phone</small><b>+92 324 7305909</b></span></div><div><Mail/><span><small>Email</small><b>info@hassanomar.site</b></span></div><div><Clock/><span><small>Working Hours</small><b>Available by appointment</b></span></div></aside></div></section><footer className="site-footer"><div><span className="footer-mh"><b>M</b><b>H</b></span><span>© {new Date().getFullYear()} Muhammad Hassan</span></div><div className="footer-socials"><a href="https://github.com/Hassan-Omar03" target="_blank" rel="noreferrer" aria-label="GitHub"><Github/></a><a href="https://www.linkedin.com/in/mohammad-hassan-6919aa111/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin/></a><a href="mailto:info@hassanomar.site" aria-label="Email"><Mail/></a><a href="https://wa.me/923247305909" target="_blank" rel="noreferrer" aria-label="WhatsApp"><MessageCircle/></a></div><a href="/privacy-policy">Privacy Policy</a></footer><a className="whatsapp-float" href="https://wa.me/923247305909?text=Hello%20Muhammad%20Hassan%2C%20I%20would%20like%20to%20discuss%20a%20project." target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><MessageCircle/><span>WhatsApp</span></a></main>}





















